#!/usr/bin/env bash

RED=$(tput setaf 1)
GRE=$(tput setaf 2)
YEL=$(tput setaf 3)
RES=$(tput sgr0)

clear
echo "$RED########################################"
echo "###             WARNING!             ###"
echo "########################################"
echo
echo "$YEL  This script will clear pacman cache!$RES"
echo
echo "Press$GRE ENTER$RES to contiue, or$GRE CTRL+C$RES to cancel."
read result

yes | sudo pacman -Scc

if [ -d out ]; then
    echo ":: Removing out folder..."
    sudo rm -rf out
fi

if [ -d work ]; then
    echo ":: Removing work folder..."
    sudo rm -rf work
fi

sudo mkarchiso -v -w work -o out wadam
